### ISSUE TITLE
A section about git standards

### ISSUE THREAD

**Issue by arlukin** [carcosa-rnd/carcosa.se#12]
Can you write a section about your git message philosophy. I think we have about the same. When to use fix: feat: etc.

Maybe a link to some good resource on internet?

It can be placed here, or if you find a better place. FYI: More development articles will be added later.
https://carcosa.se/docs/handbook/git

**Comment by theCodingJohn** [comment]
I'm following the [conventional commits](https://www.conventionalcommits.org/en/v1.0.0/) format. This cheat sheet makes it easier to understand https://megamorf.gitlab.io/cheat-sheets/conventional-commits/. Most importantly, I use imperative mood in writing commit messages https://stackoverflow.com/questions/3580013/should-i-use-past-or-present-tense-in-git-commit-messages

**Comment by arlukin** [comment]
That conventional commits is what I also try to follow. Please write a couple of sentences about that in the "handbook". So that can be kind of our home of standards.

**Comment by theCodingJohn** [comment]
all right 👍

**Comment by arlukin** [comment]
Can you also add a section about "imperative tense".
