### ISSUE TITLE
Change Favicon image

### ISSUE THREAD

**Issue by arlukin** [carcosa-rnd/carcosa.se#5]
I think the black C in the favicon wasn't that good. Probably better white. Or if you have any suggestion.

I used https://designer.gravit.io/  and this font http://fonts101.com/fonts/view/Uncategorized/28527/antlers to create the current black C. And then some random svg to favicon online tool.

**Comment by theCodingJohn** [comment]
Imo, brand/primary (cyan) color would be better. I think white color doesn't look good in light mode, so is black in dark mode

**Comment by arlukin** [comment]
You are right, primary color should match favicon.

Cyan as the primary color is not something that is totally decided. It kind of just happened and are still open for change. I have been thinking about yellow. Maybe you can fiddle around a bit. Maybe take a few screen shots with colors you like. Or links to other websites that looks good in yellow.

FYI, I'm a bit colorblind, which can explain some color combinations =)

**Comment by theCodingJohn** [comment]
What do you think about these?
![20bf55](https://user-images.githubusercontent.com/67894296/127991041-f1ad233d-3d1f-44f0-a1f3-57ea99224611.png)
![fdd007](https://user-images.githubusercontent.com/67894296/127991071-1f8221b4-e915-4721-900f-a38278ed5978.png)

![fc575e](https://user-images.githubusercontent.com/67894296/127991068-a9c2d0f7-8b67-4047-85bd-d45091f73798.png)

![f2ae54](https://user-images.githubusercontent.com/67894296/127991063-a1a6ec66-062b-46d9-bc24-a8046ff7cd25.png)

![Uploading 2021-08-03 (25).png…](
![29524a](https://user-images.githubusercontent.com/67894296/127991046-3bae2413-7cb5-4221-b9e0-16ef763a0d23.png)
![124468](https://user-images.githubusercontent.com/67894296/127991052-26af297e-31a7-4835-8bd1-e9f621343385.png)
![a40606](https://user-images.githubusercontent.com/67894296/127991055-78defc12-b3ba-4143-9808-593cde56cb9a.png)
![d98324](https://user-images.githubusercontent.com/67894296/127991058-fd2b214f-7333-4961-8ee7-de2ed3f420f0.png)

![5f0a87](https://user-images.githubusercontent.com/67894296/127991034-381f2217-399a-4440-9f67-62fd1e25897f.png)

**Comment by theCodingJohn** [comment]
colors were taken on this site https://www.eggradients.com/

**Comment by arlukin** [comment]
Thanks for the screenshots. 

What do you think about this combination? And use both the yellow and the blue? 

<img width="366" alt="Screenshot 2021-08-03 at 19 35 24" src="https://user-images.githubusercontent.com/223861/128060603-3fa34a4e-301f-4bc6-8680-30d3cd71de85.png">

**Comment by theCodingJohn** [comment]
I think yellow works really well in dark background 
![9393bc270f1dad706285fe2d2bd0321b](https://user-images.githubusercontent.com/67894296/128113987-f7a60365-16a2-4dd1-95ae-436746abf0e0.jpg)
![3764cf3d6f7f1a31efcc64eea7b8be85](https://user-images.githubusercontent.com/67894296/128113993-50898a65-a9bb-4532-84d2-33dc6b523cb7.jpg)
![yellow-website-27](https://user-images.githubusercontent.com/67894296/128113994-ecbcd942-0b04-4cd3-8173-dd41861c1019.jpg)

**Comment by theCodingJohn** [comment]
I have used a darker variation of blue as our body background instead of pure black. What do you think? 
The docs page is still in white background though

![screencapture-localhost-3000-2021-08-04-10_51_11](https://user-images.githubusercontent.com/67894296/128114333-f846a69b-1ec0-458c-87f9-b811e719e060.png)

White body

![screencapture-localhost-3000-2021-08-04-10_59_28](https://user-images.githubusercontent.com/67894296/128115211-cc8bf994-e15d-4186-8e38-c7db73731a2a.png)
I can't think of anything where to use blue

**Comment by arlukin** [comment]
I liked the first one where you used the "darker variation of blue" as background. I think you should go for that, both on the first page and the doc pages.

**Comment by arlukin** [comment]
You have done all this, and it looks good =)
